server:
  port: 9090
  servlet: 
    context-path: /SpringBoot-Mail-Notification
    
springBoot:
 app:      
   name: SpringBootCurdOptionsWithMailNotification
 welcome:
    message: welcome SpringBootCurdOptionsWithMailNotification user 

#http://localhost:9090/SpringBoot-Mail-Notification/swagger-ui.html
spring:
   jpa:
    hibernate:
      use-new-id-generator-mappings: true


     
loan:
 noOfmonths: 
    months: 12 
 interestRateAmount: 1.5

